// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: proto/message_service.proto

package message_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message represents a message in our system
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_message_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// SaveMessageRequest contains the data needed to save a new message
type SaveMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMessageRequest) Reset() {
	*x = SaveMessageRequest{}
	mi := &file_proto_message_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMessageRequest) ProtoMessage() {}

func (x *SaveMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMessageRequest.ProtoReflect.Descriptor instead.
func (*SaveMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{1}
}

func (x *SaveMessageRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SaveMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetLast10Response contains the list of last 10 messages
type GetLast10Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLast10Response) Reset() {
	*x = GetLast10Response{}
	mi := &file_proto_message_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLast10Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLast10Response) ProtoMessage() {}

func (x *GetLast10Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLast10Response.ProtoReflect.Descriptor instead.
func (*GetLast10Response) Descriptor() ([]byte, []int) {
	return file_proto_message_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLast10Response) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_proto_message_service_proto protoreflect.FileDescriptor

const file_proto_message_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/message_service.proto\x12\x0fmessage_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9c\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"B\n" +
	"\x12SaveMessageRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x11GetLast10Response\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.message_service.MessageR\bmessages2\x9e\x01\n" +
	"\x0eMessageService\x12C\n" +
	"\x04Save\x12#.message_service.SaveMessageRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\tGetLast10\x12\x16.google.protobuf.Empty\x1a\".message_service.GetLast10ResponseB.Z,cgi.com/goLangTraining/proto/message_serviceb\x06proto3"

var (
	file_proto_message_service_proto_rawDescOnce sync.Once
	file_proto_message_service_proto_rawDescData []byte
)

func file_proto_message_service_proto_rawDescGZIP() []byte {
	file_proto_message_service_proto_rawDescOnce.Do(func() {
		file_proto_message_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_service_proto_rawDesc), len(file_proto_message_service_proto_rawDesc)))
	})
	return file_proto_message_service_proto_rawDescData
}

var file_proto_message_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_message_service_proto_goTypes = []any{
	(*Message)(nil),               // 0: message_service.Message
	(*SaveMessageRequest)(nil),    // 1: message_service.SaveMessageRequest
	(*GetLast10Response)(nil),     // 2: message_service.GetLast10Response
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_proto_message_service_proto_depIdxs = []int32{
	3, // 0: message_service.Message.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: message_service.GetLast10Response.messages:type_name -> message_service.Message
	1, // 2: message_service.MessageService.Save:input_type -> message_service.SaveMessageRequest
	4, // 3: message_service.MessageService.GetLast10:input_type -> google.protobuf.Empty
	4, // 4: message_service.MessageService.Save:output_type -> google.protobuf.Empty
	2, // 5: message_service.MessageService.GetLast10:output_type -> message_service.GetLast10Response
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_message_service_proto_init() }
func file_proto_message_service_proto_init() {
	if File_proto_message_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_service_proto_rawDesc), len(file_proto_message_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_service_proto_goTypes,
		DependencyIndexes: file_proto_message_service_proto_depIdxs,
		MessageInfos:      file_proto_message_service_proto_msgTypes,
	}.Build()
	File_proto_message_service_proto = out.File
	file_proto_message_service_proto_goTypes = nil
	file_proto_message_service_proto_depIdxs = nil
}
